repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-ast
      - id: check-case-conflict
      - id: detect-private-key
      - id: debug-statements
      - id: check-toml
      - id: check-merge-conflict
      - id: fix-byte-order-marker
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.2
    hooks:
      - id: ruff
        args: [ --fix, --config ruff.toml ]
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: https://github.com/pdm-project/pdm
    rev: 2.22.2 # a PDM release exposing the hook
    hooks:
    - id: pdm-lock-check
    - id: pdm-sync
      additional_dependencies:
        - keyring
